Issue/#100 place header elements
DPigeon/Money-Tree pull request #159
Opened 2020-11-19 18:31 UTC by EspressoCode

# Related Issue
#100 

# Proposed changes
- adds the header component so that we can place it on different pages of the app
- the header is responsive to the width of the screen, if the width goes lower than 600 px it assumes that the user is using the application on his/her phone and changes to mobile version view.

# Additional Info
- some routes are created, this component will be fully functional after other pages are created, but for now, the buttons are functional.

# Reviewer(s)
 @Alessandro100 @arthur-del @marwan011

2020-11-19 19:10 UTC, Alessandro100 requested changes
Really nice stuff! It looks very similar if not identical to the Figma prototypes! The comments I left are more of refactoring type comments.

I see that your branch has conflicts with dev, we are going to have to do a git rebase. If you are unsure of how to do this, we can do it together. I also ran the tests and they failed. If you are unsure how to fix it, we can also do this together.

2020-11-19 19:10 UTC, Alessandro100 commented on client/src/app/components/header/header.component.html
> +        <span>LeaderBoard</span>
the 'B' in leaderboard doesn't need to be capitalized

2020-11-19 19:10 UTC, Alessandro100 commented on client/src/app/components/header/header.component.html
> +      </button>
I know it's not what's in the sigma prototype, but I think the mobile logout button should be in the same list / style as the other buttons

2020-11-19 19:10 UTC, Alessandro100 commented on client/src/app/components/header/header.component.scss
> +}
can you add this class in the mobile-menu-container block

2020-11-19 19:10 UTC, Alessandro100 commented on client/src/app/components/header/header.component.scss
> +}
can you add this class in the mobile-menu-container block

2020-11-19 19:10 UTC, Alessandro100 commented on client/src/app/components/header/header.component.ts
> +import { Component, OnInit, ViewEncapsulation } from '@angular/core';
you can remove 'ViewEncapsulation'

2020-11-19 20:50 UTC, EspressoCode commented on client/src/app/components/header/header.component.html
> +  </div>
ok I'll adapt it to those changes in a future commit

2020-11-19 20:52 UTC, EspressoCode commented on client/src/app/components/header/header.component.scss
> +    font-size: 50px !important;
that's true, I changed it.

2020-11-19 20:57 UTC, EspressoCode commented on client/src/app/components/header/header.component.scss
> +    font-size: 50px !important;
![log out suggestion](https://user-images.githubusercontent.com/33170291/99723198-b2d0ef00-2a66-11eb-9f40-12d7aabf9656.PNG)

I put both alternatives beside each other, I like both, let me know which one you think is better and if needed I'll change the Mockup accordingly.

2020-11-19 23:14 UTC, EspressoCode reviewed
Thanks for your detailed feedback, I made the requested changes. About moving some of the styles to the parent containers I should explain that there is weird behaviour for mat-menu items since Angular applies some styling on it, so I had to keep them separated.

2020-11-20 02:13 UTC, Alessandro100 approved these changes
Awesome changes, everything looks good! I saw that sonar cloud picked up 2 code smells:
1. An unused import -> fix this and we'll merge
2. An empty leaderboard.scss file, we can tolerate this as we know we will populate this

Remove the unused import and merge! Solid work Hossein!

2020-11-20 02:13 UTC, Alessandro100 commented on client/src/app/components/header/header.component.spec.ts
> +  NGRX_STORE_MODULE,
Hey since we don't use NGRX_STORE_MODULE we can remove it. Sonarcloud picked it up as a code smell

2020-11-20 08:22 UTC, merged