Bug/signup password validation #197
DPigeon/Money-Tree pull request #202
Opened 2020-12-10 08:57 UTC by EspressoCode

# Related Issue
- This pr is a bug fix for:  #197  

# Proposed changes
- Change the error message for prompting user to have at list one symbol in password, now by showing a given list of symbols.
- Password match should work fine now by adding a custom validator to the form (instead of dynamically setting the validator).

# Reviewer(s)
 - @Alessandro100 @wltrf  @DPigeon

2020-12-10 14:03 UTC, wltrf requested changes

2020-12-10 14:03 UTC, wltrf commented on client/src/app/components/signup-form/signup-form.component.ts
> +          return 'Password must contain at least 8 characters, including one number, one letter and one of these special characters: @$!%*#?&';
Could add: "and no space"

2020-12-10 14:11 UTC, Alessandro100 commented on client/src/app/components/signup-form/signup-form.component.ts
> +              /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/u
I have to agree with walter, I think our password for now should only have the validation of 8 character length, nothing more

2020-12-10 14:18 UTC, wltrf commented on client/src/app/components/signup-form/signup-form.component.ts
> +              /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/u
^ Thats a bit too extreme imo as the validation work is already done and works, the issues I stated above is 1. we need to accept more than 8 different special chars, and 2. we need to accept any character except whitespace for the overall password. The fix is quick and easy just replace the regex

2020-12-10 17:12 UTC, EspressoCode commented on client/src/app/components/signup-form/signup-form.component.ts
> +              /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/u
I agree, sorry that was my bad, I just copied and pasted what I had for the first part of  my regex into the second part without thinking about what exactly it does. In the new commit I fixed it.

2020-12-10 21:53 UTC, wltrf commented
![Screenshot from 2020-12-10 16-52-35](https://user-images.githubusercontent.com/33789241/101834277-261acd80-3b08-11eb-96d4-07097c3be0bb.png)
@EspressoCode @Alessandro100  Why did we remove a feature that worked?

2020-12-10 21:58 UTC, Alessandro100 requested changes
I made a small comment about writing 'UPPERCASE' in lowercase. I noticed that if you have an invalid password that doesn't match, it will prioritize showing the 'your password doesn't match' message. Would it be possible to change the priority to 'Your password needs xxxx' 

![image](https://user-images.githubusercontent.com/18631060/101834925-fc15db00-3b08-11eb-8ce9-bba20851b193.png)

2020-12-10 21:58 UTC, Alessandro100 commented on client/src/app/components/signup-form/signup-form.component.ts
> +          return 'Password must contain at least 8 characters, including one number, one lowercase and one UPPERCASE letter, and no space.';
we can write 'uppercase' in lower case

2020-12-11 13:27 UTC, wltrf approved these changes

2020-12-11 13:46 UTC, Alessandro100 approved these changes
Great fixes Hossein! Looks good to me

2020-12-11 13:46 UTC, merged